name: CI/CD Build a compose for voting app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: lear2ean

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: deploy
        run: |
          docker-compose  up -d
