name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Tag Docker image
        run: |
          docker tag my-app:latest <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.us-east-1.amazonaws.com

      - name: Push to ECR
        run: |
          docker push <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest
