name: CI/CD Build a compose for voting app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: tunde

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: deployment
        run: |
          docker compose  up -d
